kind: Secret
apiVersion: v1
metadata:
  name: app
  annotations:
    avp.kubernetes.io/remove-missing: "false"
type: Opaque
stringData:
  GOOGLE_CLIENTSECRET: "<path:kv-k8s/data/quotalab/backend-platform/admin-api/dev/dev#GOOGLE_CLIENTSECRET>"